### ISSUE TITLE
Exception reported: Invalid index XX (count: XX)

### ISSUE THREAD

**Issue by strteamservidores** [NiGHT757/Custom-MVP-Anthem#1]
Nothing in wrong on config files, and this are spamming on error log.

```
[SM] Exception reported: Invalid index 75 (count: 75)
[SM] Blaming: kento_mvp.smx
[SM] Call stack trace:
[SM]   [0] ArrayList.GetString
[SM]   [1] Line 160, C:\Users\breno\Desktop\New Update\Plugins\csgo\addons\sourcemod\scripting\kento_mvp.sp::Event_RoundMVP
```

**Comment by NiGHT757** [comment]
Fixed, sorry, I forgot to update it here.

If you want to recompile the plugin use this include https://github.com/NiGHT757/Custom-MVP-Anthem/tree/main/addons/sourcemod/scripting

Thanks.
